cpu_count: 4
packages:
  cryptography: cryptography
  dirsync: dirsync
  gputil: GPUtil
  list_imports: list-imports
  matplotlib: matplotlib --prefer-binary
  psutil: psutil
  setuptools: setuptools
version: 26.05.04a