cpu_count: 4
packages:
  attrs: attrs
  blosc2: blosc2
  cryptography: cryptography
  cython: Cython
  dcmstack: dcmstack
  dirsync: dirsync
  einops: einops
  gdown: gdown
  gitpython: GitPython
  gputil: GPUtil
  list_imports: list-imports
  lmdb: lmdb
  lmfit: lmfit
  matplotlib: matplotlib==3.7.4
  mlflow: mlflow
  mss: mss
  nibabel: nibabel
  nipy: nipy
  nipype: nipype
  nitime: nitime
  niworkflows: niworkflows
  nose: nose
  numba: numba
  numpy: numpy
  pandas: pandas
  prompt_toolkit: prompt_toolkit
  psutil: psutil
  pynrrd: pynrrd
  pyqt5: PyQt5==5.15.7
  pyqt5-sip: PyQt5-sip==12.15.0
  pyqt6: PyQt6
  pyqt6-sip: PyQt6-sip
  pytest: pytest
  python-dotenv: python-dotenv
  ray: ray
  read_roi: read_roi
  scikit-image: scikit-image
  scipy: scipy
  simpleITK: simpleITK
  sip: sip
  sympy: sympy
  tensorflow: tensorflow==2.19.0
  tkinter: tk
  traits: traits
  transformers: transformers
  typing_inspect: typing_inspect
  vedo: vedo
version: 26.05.04a